add gitee.com support.
magit/forge pull request #326
Opened 2020-12-27 04:46 UTC by loyalpartner

Your software is very good, I like it very much, but in my country we work with gitee.com, I made a little change to open the commit and issues in gitee.com in emacs, I hope you can pass this pr, so that more people can use this little feature easily.

2020-12-27 10:25 UTC, tarsius requested changes
Please update the "Partially Supported Forges" node in the manual. (Only edit `forge.org`; I will regenerate `forge.texi`.)

2020-12-27 10:25 UTC, tarsius commented on lisp/forge-core.el
> +    ;; gitee (API unsupported)
Put this below the bitbucket entry into the "Forges (API unsupported)" group. (Don't add an additional comment, the comment I just mentioned covers that.)

2020-12-27 10:25 UTC, tarsius commented on lisp/forge-gitee.el
> +;;; forge-bitbucket.el --- Bitbucket support      -*- lexical-binding: t -*-
You forgot to adjust this. When you edit this make sure `-*- lexical-binding: t -*-` begins at the same column as before.

2020-12-27 10:26 UTC, tarsius commented on lisp/forge-core.el
> +     "gitee.com" forge-gitee-repository))
Put this below the bitbucket entry into the "Forges (API unsupported)" group. (Don't add an additional comment, the comment I just mentioned covers that.)

2020-12-27 11:01 UTC, loyalpartner commented
Thank you for your guidance, I have changed according to what you said。

2020-12-27 20:43 UTC, tarsius commented
You omitted many of the slots that are set for many of the other classes.  Why?

2020-12-28 14:21 UTC, loyalpartner commented
i use M-x "forge-" to found the relation with them, but i can't found how to use them ,so i omit it.

2020-12-28 14:30 UTC, tarsius commented
> i use M-x "forge-" to found the relation with them, but i can't found how to use them ,so i omit it.

Some or even all of those are indeed unused. At present. I have added these slots because I expect to be using them eventually. Once that happens the values will already be ready to use for all forges that are currently supported. It would be nice if that also applied to gitee.com, especially because I don't use that myself, which means it would be more work for me to do it then than it would be for you to do it now.

2020-12-28 14:32 UTC, tarsius commented
I notice you added the suggested commit summary when squashing the commits. Unfortunately you also added the period at the end of the summary back again. Please remove that like for all other commits in this repository.

2021-01-02 13:43 UTC, tarsius commented
Please let me know when you have added the missing slots, then we can still add this.

2021-01-02 13:43 UTC, closed without merging

2021-01-05 19:46 UTC, tarsius commented
I have added [a faq entry](https://github.com/magit/forge/wiki/FAQ#do-you-plan-to-addextend-support-forge-x) about the forges I plan or don't plan to support. Because I do not plan to implement support for this particular forge I am closing this issue. That doesn't mean that you cannot comment here or shouldn't discourage you from contributing support for favorite forge yourself.